# Generated by Django 5.0 on 2024-12-01 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_tag_blogpost_estimated_read_time_and_more'),
        ('leads', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedownload',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_downloads', to='leads.newslettersubscription'),
        ),
        migrations.RemoveField(
            model_name='resourcedownload',
            name='converted_to_subscriber',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
