# Generated by Django 5.0 on 2024-12-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_campaign_landingpage_abtest_variant_variantvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.JSONField()),
                ('implementation_timeline', models.TextField()),
                ('testimonial', models.TextField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
