# Generated by Django 5.0 on 2024-12-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_casestudy"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Brief summary for cards and previews"
            ),
        ),
    ]
