# Generated by Django 5.0 on 2024-12-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_add_case_study_category"),
    ]

    operations = []
