# Generated by Django 5.1.3 on 2025-03-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_populate_case_study_categories"),
        ("leads", "0008_contact_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceleratorQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_score", models.FloatField(null=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accelerator_quizzes",
                        to="leads.newslettersubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DimensionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("Data Trust Engine", "Data Trust Engine"),
                            ("Data Rulebook", "Data Rulebook"),
                            ("AI Power Grid", "AI Power Grid"),
                            ("Data Flow Superhighway", "Data Flow Superhighway"),
                            ("AI Fuel Factory", "AI Fuel Factory"),
                            ("AI Mindset Shift", "AI Mindset Shift"),
                            ("AI Deployment Machine", "AI Deployment Machine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("score", models.IntegerField()),
                ("answers", models.JSONField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension_scores",
                        to="content.acceleratorquiz",
                    ),
                ),
            ],
        ),
    ]
