# Generated by Django 5.1.3 on 2025-03-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_acceleratorquiz_dimensionscore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceleratorquiz",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Accelerator Quizzes",
            },
        ),
        migrations.AlterModelOptions(
            name="dimensionscore",
            options={"ordering": ["quiz", "dimension"]},
        ),
        migrations.AlterUniqueTogether(
            name="dimensionscore",
            unique_together={("quiz", "dimension")},
        ),
    ]
