# Generated by Django 5.0 on 2024-11-16 23:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website Form'), ('BLOG', 'Blog Subscription'), ('RESOURCE', 'Resource Download'), ('REFERRAL', 'Referral'), ('SOCIAL', 'Social Media'), ('OTHER', 'Other')], default='WEBSITE', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal Sent'), ('NEGOTIATION', 'In Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('INACTIVE', 'Inactive')], default='NEW', max_length=50)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Phone Call'), ('MEETING', 'Meeting'), ('DOWNLOAD', 'Resource Download'), ('FORM', 'Form Submission'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('DEMOGRAPHIC', 'Demographic'), ('BEHAVIORAL', 'Behavioral'), ('ENGAGEMENT', 'Engagement')], max_length=50)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='leads.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ROICalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_team_size', models.IntegerField()),
                ('technology_spend', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_efficiency', models.IntegerField(help_text='Current efficiency percentage')),
                ('projected_efficiency', models.IntegerField(help_text='Projected efficiency percentage')),
                ('annual_savings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('roi_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payback_months', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_calculations', to='leads.contact')),
            ],
        ),
    ]
