# Generated by Django 5.0 on 2024-12-08 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('anonymous_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('current_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('source_of_first_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.TextField(blank=True)),
                ('marketing_consent', models.BooleanField(default=True)),
                ('analytics_consent', models.BooleanField(default=True)),
                ('consent_updated_at', models.DateTimeField(blank=True, null=True)),
                ('merged_with', models.ForeignKey(blank=True, help_text='Points to the primary identity if this was merged', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_identities', to='leads.identity')),
            ],
            options={
                'verbose_name_plural': 'Identities',
                'indexes': [models.Index(fields=['anonymous_id'], name='leads_ident_anonymo_5d8151_idx'), models.Index(fields=['primary_email'], name='leads_ident_primary_9e1838_idx'), models.Index(fields=['current_session_id'], name='leads_ident_current_7a03fa_idx')],
            },
        ),
    ]
