# Generated by Django 5.1.3 on 2024-12-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='leads.identity')),
            ],
            options={
                'verbose_name': 'Identity Email',
                'verbose_name_plural': 'Identity Emails',
                'ordering': ['-is_primary', '-last_used_at'],
                'indexes': [models.Index(fields=['email'], name='leads_ident_email_3458f3_idx'), models.Index(fields=['identity', 'is_primary'], name='leads_ident_identit_47c957_idx')],
            },
        ),
    ]
