# Generated by Django 5.0 on 2024-12-08 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_identityemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='Unique device fingerprint hash', max_length=255)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this device was first associated with the identity')),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='Last time this device was active')),
                ('user_agent', models.TextField(blank=True, help_text='Last known user agent string', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is still actively used')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='leads.identity')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['fingerprint'], name='leads_ident_fingerp_7ec2af_idx'), models.Index(fields=['last_seen_at'], name='leads_ident_last_se_a03dde_idx')],
                'unique_together': {('identity', 'fingerprint')},
            },
        ),
    ]
