# Generated by Django 5.0 on 2024-12-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_identitydevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
