# Generated by Django 5.0 on 2024-12-08 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_identity_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='identity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='leads.identity'),
        ),
    ]
