[build]
builder = "nixpacks"

[deploy]
startCommand = """
python manage.py migrate --noinput && \
python manage.py collectstatic --noinput && \
gunicorn core.wsgi:application --bind 0.0.0.0:8080
"""
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
internal_port = 8080

[env]
PYTHONUNBUFFERED = "1"
