[build]
builder = "nixpacks"

[deploy]
startCommand = "/opt/venv/bin/gunicorn --workers=2 --threads=4 --timeout=0 --bind=0.0.0.0:8080 core.wsgi:application"
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
internal_port = 8080
