[build]
builder = "nixpacks"

[deploy]
startCommand = """
/opt/venv/bin/python manage.py migrate && \
/opt/venv/bin/python manage.py collectstatic --noinput && \
/opt/venv/bin/gunicorn core.wsgi:application
"""
healthcheckPath = "/admin/login/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
internal_port = 8000
