[build]
builder = "nixpacks"

[deploy]
startCommand = """
DJANGO_SETTINGS_MODULE=core.settings_prod \
python manage.py migrate --noinput && \
python manage.py collectstatic --noinput && \
/opt/venv/bin/gunicorn -c gunicorn.conf.py core.wsgi:application
"""
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
port = 8080

[service]
internal_port = 8080

# Add environment variables
[variables]
PYTHON_VERSION = "3.11"
DJANGO_SETTINGS_MODULE = "core.settings_prod"
