[build]
builder = "nixpacks"

[deploy]
startCommand = "mkdir -p staticfiles && python manage.py collectstatic --noinput && python manage.py migrate --noinput && /opt/venv/bin/gunicorn -c gunicorn.conf.py core.wsgi:application"
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
