[build]
builder = "nixpacks"

[deploy]
startCommand = """
/opt/venv/bin/python manage.py check && \
/opt/venv/bin/python manage.py migrate && \
/opt/venv/bin/python manage.py collectstatic --noinput --verbosity 2 && \
/opt/venv/bin/gunicorn core.wsgi:application --bind 0.0.0.0:8000 --log-level debug --timeout 120
"""
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
internal_port = 8000

[build.env]
PYTHONUNBUFFERED = "1"
