[build]
builder = "nixpacks"
buildCommand = """
apt-get update && apt-get install -y python3 python3-pip
python3 -m pip install --upgrade pip
pip3 install -r requirements.txt
"""

[deploy]
startCommand = """
python3 manage.py migrate && \
python3 manage.py collectstatic --noinput && \
gunicorn core.wsgi:application
"""
healthcheckPath = "/admin/login/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
internal_port = 8000
